export default [
  {
    name: 'Sport',
    category: 'sport',
    dataAt: 'at-category-sport',
    bgColor: 'sportBgColor',
    imgSrc: '/images/sport.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Coronavirus',
    category: 'coronavirus',
    dataAt: 'at-category-coronavirus',
    bgColor: 'coronaBgColor',
    imgSrc: '/images/coronavirus.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Trump',
    category: 'trump',
    dataAt: 'at-category-trump',
    bgColor: 'trampBgColor',
    imgSrc: '/images/trump.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Health',
    category: 'health',
    dataAt: 'at-category-health',
    bgColor: 'healthBgColor',
    imgSrc: '/images/health.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Food',
    category: 'food',
    dataAt: 'at-category-food',
    bgColor: 'foodBgColor',
    imgSrc: '/images/food.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Bitcoin',
    category: 'bitcoin',
    dataAt: 'at-category-bitcoin',
    bgColor: 'bitcoinBgColor',
    imgSrc: '/images/bitcoin.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Science',
    category: 'science',
    dataAt: 'at-category-science',
    bgColor: 'scienceBgColor',
    imgSrc: '/images/science.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
  {
    name: 'Travel',
    category: 'travel',
    dataAt: 'at-category-travel',
    bgColor: 'travelBgColor',
    imgSrc: '/images/travel.svg',
    titleBg: 'categoryTitle',
    textColor: 'textColor',
  },
];
