import colorMatrix from '../colorMatrix';

export default {
  categoryPage: {
    mainBgColor: colorMatrix.color__01,
    headerBgColor: colorMatrix.color__18,
    titleColor: colorMatrix.color__03,
    sportBgColor: colorMatrix.color__06,
    coronaBgColor: colorMatrix.color__07,
    trampBgColor: colorMatrix.color__08,
    healthBgColor: colorMatrix.color__09,
    foodBgColor: colorMatrix.color__10,
    bitcoinBgColor: colorMatrix.color__11,
    scienceBgColor: colorMatrix.color__12,
    travelBgColor: colorMatrix.color__13,
    otherBgColor: colorMatrix.color__14,
    categoryTitle: colorMatrix.color__15,
    textColor: colorMatrix.color__16,
    containerBgColor: colorMatrix.color__17,
    boxShadow: colorMatrix.color__02,
  },
  newsPage: {
    mainBgColor: colorMatrix.color__01,
    containerBgColor: colorMatrix.color__17,
    boxShadow: colorMatrix.color__02,
    datePickerBorder: colorMatrix.color__02,
    linkColor: colorMatrix.color__26,
    newsBgColor: colorMatrix.color__20,
    headerNewsColor: colorMatrix.color__25,
    newsGradBgGrey: colorMatrix.color__19,
    filterBlockBg: colorMatrix.color__21,
    buttonBg: colorMatrix.color__22,
    buttonBgHover: colorMatrix.color__23,
    textColor: colorMatrix.color__04,
    redBorder: colorMatrix.color__27,
    spinnerColorTheme: colorMatrix.color__23,
    languageColor: colorMatrix.color__10,
  },
};
