export const languagePickerButtons = [
  {
    content: 'english',
    onClickCallback: 'changeLanguage',
    value: 'en',
    id: 'english',
    dataAt: 'data-at-english-language-button',
    flag: 'gb',
  },
  {
    content: 'deutschland',
    onClickCallback: 'changeLanguage',
    value: 'de',
    id: 'deutschland',
    dataAt: 'data-at-deutschland-language-button',
    flag: 'de',
  },
  {
    content: 'france',
    onClickCallback: 'changeLanguage',
    value: 'fr',
    id: 'france',
    dataAt: 'data-at-france-language-button',
    flag: 'fr',
  },
  {
    content: 'spain',
    onClickCallback: 'changeLanguage',
    value: 'es',
    id: 'spain',
    dataAt: 'data-at-spain-language-button',
    flag: 'es',
  },
  {
    content: 'russian',
    onClickCallback: 'changeLanguage',
    value: 'ru',
    id: 'russian',
    dataAt: 'data-at-russian-language-button',
    flag: 'ru',
  },
];
